#include <stdio.h>
#include <stdlib.h> //for atoi
#include "opt_file.h"

#define LINE_LENGTH_BUFFER_SIZE 256

typedef struct BugTypeTAG {
    char *fun1,*fun2,*scope,*bug;

    float confidence;
}BugType,*BugTypeHANDLE;



/** @brief A structure to hold a list of callees.
  * 
  * This structure holds a list of all callees in a scope.
  * Internally it uses a linked list structure with each node representing a
  * single scope in the file.
  */
typedef struct CalleeListTAG {
    char *name;

    struct CalleeListTAG *next;
}CalleeList;

/** @brief A structure to hold a parsed file.
  * 
  * This structure holds a parsed bitcode file generated by the LLVM opt tool.
  * Internally it uses a linked list structure with each node representing a
  * single scope in the file.
  */
typedef struct ParsedFileTAG {
    char *fname;
    CalleeList *callees;

    struct ParsedFileTAG *next;
}ParsedFile;

typedef struct FunctionDataTAG {
    int id; // <-- the function 'name'
    int refCount; // <-- how many times this function is referenced
    int numCallees; // <-- how many functions this function calls
    int *callees; // <-- an array of the functions this function calls in order
}FunctionData,*FunctionDataHANDLE;
typedef struct CallingMapTAG {
    int numFunctions;
    FunctionData *functions;
} CallingMap,*CallingMapHANDLE;

int main(int argc, char *argv[])
{
    char *input_file_name = argv[1];
    
    FILE *input_file = fopen(input_file_name,"r");
    
    char buf[LINE_LENGTH_BUFFER_SIZE];
    fgets(buf,LINE_LENGTH_BUFFER_SIZE,input_file);//get rid of the entry point line

    while (buf[0]!='\n')
        fgets(buf,LINE_LENGTH_BUFFER_SIZE,input_file);//get rid of <null function>

    ParsedFile *pf = parse_opt_file(input_file);

    while (pf)
    {
        printf("Scope: %s\n",pf->fname);
        while (pf->callees)
        {
            printf("    %s\n",pf->callees->name);
            pf->callees = pf->callees->next;
        }
        pf = pf->next;
    }
//    free_parsed_file(sv); // if we hadn't destroyed pf->callees this should work
    return 0;
}
     
