#ifndef OPT_FILE_DEF_H
#define OPT_FILE_DEF_H 1.0

/** @brief A structure to hold a list of callees.
  * 
  * This structure holds a list of all callees in a scope.
  * Internally it uses a linked list structure with each node representing a
  * single scope in the file.
  */
typedef struct CalleeListTAG {
    char *name;

    struct CalleeListTAG *next;
}CalleeList;

/** @brief A structure to hold a parsed file.
  * 
  * This structure holds a parsed bitcode file generated by the LLVM opt tool.
  * Internally it uses a linked list structure with each node representing a
  * single scope in the file.
  */
typedef struct ParsedFileTAG {
    char *fname;
    CalleeList *callees;

    struct ParsedFileTAG *next;
}ParsedFile;

#endif // OPT_FILE_DEF_H
